// Code generated by "stringer -type=ProblemKind -linecomment -output=problem_kind_string.go"; DO NOT EDIT.

package report

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindError-0]
	_ = x[KindWarning-1]
}

const _ProblemKind_name = "errorwarning"

var _ProblemKind_index = [...]uint8{0, 5, 12}

func (i ProblemKind) String() string {
	if i >= ProblemKind(len(_ProblemKind_index)-1) {
		return "ProblemKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProblemKind_name[_ProblemKind_index[i]:_ProblemKind_index[i+1]]
}
