// Code generated by "stringer -type=PrimitiveKind -linecomment -output=primitive_kind_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownPrimitiveKind-0]
	_ = x[KindUntypedBool-1]
	_ = x[KindUntypedInt-2]
	_ = x[KindUntypedFloat-3]
	_ = x[KindUntypedString-4]
	_ = x[KindBool-5]
	_ = x[KindI8-6]
	_ = x[KindI16-7]
	_ = x[KindI32-8]
	_ = x[KindI64-9]
	_ = x[KindU8-10]
	_ = x[KindU16-11]
	_ = x[KindU32-12]
	_ = x[KindU64-13]
	_ = x[KindF32-14]
	_ = x[KindF64-15]
	_ = x[KindChar-16]
	_ = x[KindAny-17]
	_ = x[KindAnyTypeDesc-18]
}

const _PrimitiveKind_name = "UnknownPrimitiveKinduntyped booluntyped intuntyped floatuntyped stringbooli8i16i32i64u8u16u32u64f32f64charanytypedesc"

var _PrimitiveKind_index = [...]uint8{0, 20, 32, 43, 56, 70, 74, 76, 79, 82, 85, 87, 90, 93, 96, 99, 102, 106, 109, 117}

func (i PrimitiveKind) String() string {
	if i >= PrimitiveKind(len(_PrimitiveKind_index)-1) {
		return "PrimitiveKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrimitiveKind_name[_PrimitiveKind_index[i]:_PrimitiveKind_index[i+1]]
}
