// Code generated by "stringer -type=PrimitiveKind -linecomment -output=primitive_kind_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownPrimitiveKind-0]
	_ = x[KindUntypedBool-1]
	_ = x[KindUntypedInt-2]
	_ = x[KindUntypedFloat-3]
	_ = x[KindUntypedString-4]
	_ = x[KindBool-5]
	_ = x[KindI32-6]
	_ = x[KindU8-7]
	_ = x[KindAny-8]
	_ = x[KindAnyTypeDesc-9]
}

const _PrimitiveKind_name = "UnknownPrimitiveKinduntyped booluntyped intuntyped floatuntyped stringbooli32u8anytypedesc"

var _PrimitiveKind_index = [...]uint8{0, 20, 32, 43, 56, 70, 74, 77, 79, 82, 90}

func (i PrimitiveKind) String() string {
	if i >= PrimitiveKind(len(_PrimitiveKind_index)-1) {
		return "PrimitiveKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrimitiveKind_name[_PrimitiveKind_index[i]:_PrimitiveKind_index[i+1]]
}
