// Code generated by "stringer -type=PrimitiveKind -linecomment -output=primitive_kind_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindUntypedBool-1]
	_ = x[KindUntypedInt-2]
	_ = x[KindUntypedFloat-3]
	_ = x[KindUntypedString-4]
	_ = x[KindBool-5]
	_ = x[KindI8-6]
	_ = x[KindI16-7]
	_ = x[KindI32-8]
	_ = x[KindI64-9]
	_ = x[KindU8-10]
	_ = x[KindU16-11]
	_ = x[KindU32-12]
	_ = x[KindU64-13]
	_ = x[KindF32-14]
	_ = x[KindF64-15]
	_ = x[KindChar-16]
	_ = x[KindPointer-17]
	_ = x[KindAny-18]
	_ = x[KindAnyTypeDesc-19]
}

const _PrimitiveKind_name = "untyped booluntyped intuntyped floatuntyped stringbooli8i16i32i64u8u16u32u64f32f64charpointeranytypedesc"

var _PrimitiveKind_index = [...]uint8{0, 12, 23, 36, 50, 54, 56, 59, 62, 65, 67, 70, 73, 76, 79, 82, 86, 93, 96, 104}

func (i PrimitiveKind) String() string {
	i -= 1
	if i >= PrimitiveKind(len(_PrimitiveKind_index)-1) {
		return "PrimitiveKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PrimitiveKind_name[_PrimitiveKind_index[i]:_PrimitiveKind_index[i+1]]
}
