// Code generated by "stringer -type=Kind -output=kind_user_string.go -linecomment"; DO NOT EDIT.
// NOTE names was chaged!

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Comment-2]
	_ = x[Whitespace-3]
	_ = x[NewLine-4]
	_ = x[Attribute-5]
	_ = x[Ident-6]
	_ = x[Int-7]
	_ = x[Float-8]
	_ = x[String-9]
	_ = x[LParen-10]
	_ = x[RParen-11]
	_ = x[LCurly-12]
	_ = x[RCurly-13]
	_ = x[LBracket-14]
	_ = x[RBracket-15]
	_ = x[Comma-16]
	_ = x[Colon-17]
	_ = x[Semicolon-18]
	_ = x[Eq-19]
	_ = x[EqOp-20]
	_ = x[Bang-21]
	_ = x[NeOp-22]
	_ = x[LtOp-23]
	_ = x[LeOp-24]
	_ = x[GtOp-25]
	_ = x[GeOp-26]
	_ = x[Plus-27]
	_ = x[PlusEq-28]
	_ = x[Minus-29]
	_ = x[MinusEq-30]
	_ = x[Asterisk-31]
	_ = x[AsteriskEq-32]
	_ = x[Slash-33]
	_ = x[SlashEq-34]
	_ = x[Percent-35]
	_ = x[PercentEq-36]
	_ = x[Amp-37]
	_ = x[At-38]
	_ = x[QuestionMark-39]
	_ = x[Arrow-40]
	_ = x[FatArrow-41]
	_ = x[Dot-42]
	_ = x[Dot2-43]
	_ = x[Dot2Less-44]
	_ = x[Ellipsis-45]
	_ = x[KwModule-46]
	_ = x[KwAlias-47]
	_ = x[KwStruct-48]
	_ = x[KwEnum-49]
	_ = x[KwFunc-50]
	_ = x[KwVal-51]
	_ = x[KwVar-52]
	_ = x[KwConst-53]
	_ = x[KwOf-54]
	_ = x[KwIf-55]
	_ = x[KwElse-56]
	_ = x[KwWhile-57]
	_ = x[KwReturn-58]
	_ = x[KwBreak-59]
	_ = x[KwContinue-60]
}

const _Kind_user_name = "illegal characterend of fileany commentwhitespacenew lineattributeidentifieruntyped intuntyped floatuntyped string'('')''{''}''['']'','':'';'operator '='operator '=='operator '!'operator '!='operator '<'operator '<='operator '>'operator '>='operator '+'operator '+='operator '-'operator '-='operator '*'operator '*='operator '/'operator '/='operator '%'operator '%='operator '&'operator '@'operator '?'operator '->'operator '=>'operator '.'operator '..'operator '..<'operator '...'keyword 'module'keyword 'alias'keyword 'struct'keyword 'enum'keyword 'func'keyword 'val'keyword 'var'keyword 'const'keyword 'of'keyword 'if'keyword 'else'keyword 'while'keyword 'return'keyword 'break'keyword 'continue'"

var _Kind_user_index = [...]uint16{0, 17, 28, 39, 49, 57, 66, 76, 87, 100, 114, 117, 120, 123, 126, 129, 132, 135, 138, 141, 153, 166, 178, 191, 203, 216, 228, 241, 253, 266, 278, 291, 303, 316, 328, 341, 353, 366, 378, 390, 402, 415, 428, 440, 453, 467, 481, 497, 512, 528, 542, 556, 569, 582, 597, 609, 621, 635, 650, 666, 681, 699}

func (i Kind) UserString() string {
	if i >= Kind(len(_Kind_user_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_user_name[_Kind_user_index[i]:_Kind_user_index[i+1]]
}
