// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Comment-2]
	_ = x[Whitespace-3]
	_ = x[Tab-4]
	_ = x[NewLine-5]
	_ = x[Ident-6]
	_ = x[Int-7]
	_ = x[Float-8]
	_ = x[String-9]
	_ = x[LParen-10]
	_ = x[RParen-11]
	_ = x[LCurly-12]
	_ = x[RCurly-13]
	_ = x[LBracket-14]
	_ = x[RBracket-15]
	_ = x[Comma-16]
	_ = x[Colon-17]
	_ = x[Semicolon-18]
	_ = x[Eq-19]
	_ = x[EqOp-20]
	_ = x[Bang-21]
	_ = x[NeOp-22]
	_ = x[LtOp-23]
	_ = x[LeOp-24]
	_ = x[GtOp-25]
	_ = x[GeOp-26]
	_ = x[Plus-27]
	_ = x[PlusEq-28]
	_ = x[Minus-29]
	_ = x[MinusEq-30]
	_ = x[Asterisk-31]
	_ = x[AsteriskEq-32]
	_ = x[Slash-33]
	_ = x[SlashEq-34]
	_ = x[Percent-35]
	_ = x[PercentEq-36]
	_ = x[Amp-37]
	_ = x[Pipe-38]
	_ = x[Caret-39]
	_ = x[At-40]
	_ = x[QuestionMark-41]
	_ = x[QuestionMarkDot-42]
	_ = x[Arrow-43]
	_ = x[FatArrow-44]
	_ = x[Shl-45]
	_ = x[Shr-46]
	_ = x[Dot-47]
	_ = x[Dot2-48]
	_ = x[Dot2Less-49]
	_ = x[Ellipsis-50]
	_ = x[KwAnd-51]
	_ = x[KwOr-52]
	_ = x[KwModule-53]
	_ = x[KwImport-54]
	_ = x[KwAlias-55]
	_ = x[KwStruct-56]
	_ = x[KwEnum-57]
	_ = x[KwFunc-58]
	_ = x[KwVal-59]
	_ = x[KwVar-60]
	_ = x[KwConst-61]
	_ = x[KwOf-62]
	_ = x[KwIf-63]
	_ = x[KwElse-64]
	_ = x[KwWhile-65]
	_ = x[KwReturn-66]
	_ = x[KwBreak-67]
	_ = x[KwContinue-68]
}

const _Kind_name = "IllegalEOFCommentWhitespaceTabNewLineIdentIntFloatStringLParenRParenLCurlyRCurlyLBracketRBracketCommaColonSemicolonEqEqOpBangNeOpLtOpLeOpGtOpGeOpPlusPlusEqMinusMinusEqAsteriskAsteriskEqSlashSlashEqPercentPercentEqAmpPipeCaretAtQuestionMarkQuestionMarkDotArrowFatArrowShlShrDotDot2Dot2LessEllipsisKwAndKwOrKwModuleKwImportKwAliasKwStructKwEnumKwFuncKwValKwVarKwConstKwOfKwIfKwElseKwWhileKwReturnKwBreakKwContinue"

var _Kind_index = [...]uint16{0, 7, 10, 17, 27, 30, 37, 42, 45, 50, 56, 62, 68, 74, 80, 88, 96, 101, 106, 115, 117, 121, 125, 129, 133, 137, 141, 145, 149, 155, 160, 167, 175, 185, 190, 197, 204, 213, 216, 220, 225, 227, 239, 254, 259, 267, 270, 273, 276, 280, 288, 296, 301, 305, 313, 321, 328, 336, 342, 348, 353, 358, 365, 369, 373, 379, 386, 394, 401, 411}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
