// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Comment-2]
	_ = x[Type-3]
	_ = x[Name-4]
	_ = x[Underscore-5]
	_ = x[Int-6]
	_ = x[Float-7]
	_ = x[String-8]
	_ = x[LParen-9]
	_ = x[RParen-10]
	_ = x[LCurly-11]
	_ = x[RCurly-12]
	_ = x[LBracket-13]
	_ = x[RBracket-14]
	_ = x[Colon-15]
	_ = x[Comma-16]
	_ = x[Eq-17]
	_ = x[EqOp-18]
	_ = x[Bang-19]
	_ = x[NeOp-20]
	_ = x[LtOp-21]
	_ = x[LeOp-22]
	_ = x[GtOp-23]
	_ = x[GeOp-24]
	_ = x[Shl-25]
	_ = x[ShlEq-26]
	_ = x[Shr-27]
	_ = x[ShrEq-28]
	_ = x[Plus-29]
	_ = x[PlusEq-30]
	_ = x[Minus-31]
	_ = x[MinusEq-32]
	_ = x[Asterisk-33]
	_ = x[AsteriskEq-34]
	_ = x[Slash-35]
	_ = x[SlashEq-36]
	_ = x[Percent-37]
	_ = x[PercentEq-38]
	_ = x[Caret-39]
	_ = x[CaretEq-40]
	_ = x[Amp-41]
	_ = x[AmpEq-42]
	_ = x[And-43]
	_ = x[AndEq-44]
	_ = x[Pipe-45]
	_ = x[PipeEq-46]
	_ = x[Or-47]
	_ = x[OrEq-48]
	_ = x[Arrow-49]
	_ = x[FatArrow-50]
	_ = x[Dot-51]
	_ = x[Dot2-52]
	_ = x[KwLet-53]
	_ = x[KwType-54]
	_ = x[KwWhen-55]
	_ = x[KwIf-56]
	_ = x[KwElse-57]
	_ = x[KwIn-58]
	_ = x[KwAs-59]
	_ = x[KwDefer-60]
	_ = x[KwBreak-61]
	_ = x[KwReturn-62]
	_ = x[KwContinue-63]
}

const _Kind_name = "IllegalEOFCommentTypeNameUnderscoreIntFloatStringLParenRParenLCurlyRCurlyLBracketRBracketColonCommaEqEqOpBangNeOpLtOpLeOpGtOpGeOpShlShlEqShrShrEqPlusPlusEqMinusMinusEqAsteriskAsteriskEqSlashSlashEqPercentPercentEqCaretCaretEqAmpAmpEqAndAndEqPipePipeEqOrOrEqArrowFatArrowDotDot2KwLetKwTypeKwWhenKwIfKwElseKwInKwAsKwDeferKwBreakKwReturnKwContinue"

var _Kind_index = [...]uint16{0, 7, 10, 17, 21, 25, 35, 38, 43, 49, 55, 61, 67, 73, 81, 89, 94, 99, 101, 105, 109, 113, 117, 121, 125, 129, 132, 137, 140, 145, 149, 155, 160, 167, 175, 185, 190, 197, 204, 213, 218, 225, 228, 233, 236, 241, 245, 251, 253, 257, 262, 270, 273, 277, 282, 288, 294, 298, 304, 308, 312, 319, 326, 334, 344}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
