// Code generated by "stringer -type=Kind -output=kind_user_string.go -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Comment-2]
	_ = x[Whitespace-3]
	_ = x[NewLine-4]
	_ = x[Ident-5]
	_ = x[Int-6]
	_ = x[Float-7]
	_ = x[String-8]
	_ = x[LParen-9]
	_ = x[RParen-10]
	_ = x[LCurly-11]
	_ = x[RCurly-12]
	_ = x[LBracket-13]
	_ = x[RBracket-14]
	_ = x[Comma-15]
	_ = x[Colon-16]
	_ = x[Semicolon-17]
	_ = x[Eq-18]
	_ = x[EqOp-19]
	_ = x[Bang-20]
	_ = x[NeOp-21]
	_ = x[LtOp-22]
	_ = x[LeOp-23]
	_ = x[GtOp-24]
	_ = x[GeOp-25]
	_ = x[Plus-26]
	_ = x[PlusEq-27]
	_ = x[Minus-28]
	_ = x[MinusEq-29]
	_ = x[Asterisk-30]
	_ = x[AsteriskEq-31]
	_ = x[Slash-32]
	_ = x[SlashEq-33]
	_ = x[Percent-34]
	_ = x[PercentEq-35]
	_ = x[Amp-36]
	_ = x[At-37]
	_ = x[QuestionMark-38]
	_ = x[Arrow-39]
	_ = x[FatArrow-40]
	_ = x[Dot-41]
	_ = x[Dot2-42]
	_ = x[Dot2Less-43]
	_ = x[Ellipsis-44]
	_ = x[KwModule-45]
	_ = x[KwAlias-46]
	_ = x[KwStruct-47]
	_ = x[KwEnum-48]
	_ = x[KwFunc-49]
	_ = x[KwVal-50]
	_ = x[KwVar-51]
	_ = x[KwConst-52]
	_ = x[KwOf-53]
	_ = x[KwIf-54]
	_ = x[KwElse-55]
	_ = x[KwWhile-56]
	_ = x[KwReturn-57]
	_ = x[KwBreak-58]
	_ = x[KwContinue-59]
}

const _Kind_user_name = "illegal characterend of fileany commentwhitespacenew lineidentifieruntyped intuntyped floatuntyped string'('')''{''}''['']'','':'';'operator '='operator '=='operator '!'operator '!='operator '<'operator '<='operator '>'operator '>='operator '+'operator '+='operator '-'operator '-='operator '*'operator '*='operator '/'operator '/='operator '%'operator '%='operator '&'operator '@'operator '?'operator '->'operator '=>'operator '.'operator '..'operator '..<'operator '...'keyword 'module'keyword 'alias'keyword 'struct'keyword 'enum'keyword 'func'keyword 'val'keyword 'var'keyword 'const'keyword 'of'keyword 'if'keyword 'else'keyword 'while'keyword 'return'keyword 'break'keyword 'continue'"

var _Kind_user_index = [...]uint16{0, 17, 28, 39, 49, 57, 67, 78, 91, 105, 108, 111, 114, 117, 120, 123, 126, 129, 132, 144, 157, 169, 182, 194, 207, 219, 232, 244, 257, 269, 282, 294, 307, 319, 332, 344, 357, 369, 381, 393, 406, 419, 431, 444, 458, 472, 488, 503, 519, 533, 547, 560, 573, 588, 600, 612, 626, 641, 657, 672, 690}

func (i Kind) UserString() string {
	if i >= Kind(len(_Kind_user_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_user_name[_Kind_user_index[i]:_Kind_user_index[i+1]]
}
