// Code generated by "stringer -type=LiteralKind -linecomment -output=literal_kind_string.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownLiteral-0]
	_ = x[IntLiteral-1]
	_ = x[FloatLiteral-2]
	_ = x[StringLiteral-3]
}

const _LiteralKind_name = "unknown literal kindintfloatstring"

var _LiteralKind_index = [...]uint8{0, 20, 23, 28, 34}

func (i LiteralKind) String() string {
	if i >= LiteralKind(len(_LiteralKind_index)-1) {
		return "LiteralKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LiteralKind_name[_LiteralKind_index[i]:_LiteralKind_index[i+1]]
}
