// Code generated by "stringer -type=OperatorKind -linecomment -output=operator_kind_string.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownOperator-0]
	_ = x[OperatorNot-1]
	_ = x[OperatorNeg-2]
	_ = x[OperatorAddr-3]
	_ = x[OperatorMutAddr-4]
	_ = x[OperatorDeref-5]
	_ = x[OperatorAssign-6]
	_ = x[OperatorAdd-7]
	_ = x[OperatorSub-8]
	_ = x[OperatorMul-9]
	_ = x[OperatorDiv-10]
	_ = x[OperatorMod-11]
	_ = x[OperatorEq-12]
	_ = x[OperatorNe-13]
	_ = x[OperatorLt-14]
	_ = x[OperatorLe-15]
	_ = x[OperatorGt-16]
	_ = x[OperatorGe-17]
	_ = x[OperatorBitAnd-18]
	_ = x[OperatorBitOr-19]
	_ = x[OperatorBitXor-20]
	_ = x[OperatorBitShl-21]
	_ = x[OperatorBitShr-22]
	_ = x[OperatorAnd-23]
	_ = x[OperatorOr-24]
}

const _OperatorKind_name = "UnknownOperator!-&&var*=+-*/%==!=<<=>>=&|^<<>>andor"

var _OperatorKind_index = [...]uint8{0, 15, 16, 17, 18, 22, 23, 24, 25, 26, 27, 28, 29, 31, 33, 34, 36, 37, 39, 40, 41, 42, 44, 46, 49, 51}

func (i OperatorKind) String() string {
	if i >= OperatorKind(len(_OperatorKind_index)-1) {
		return "OperatorKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperatorKind_name[_OperatorKind_index[i]:_OperatorKind_index[i+1]]
}
