// Code generated by "stringer -type=OperatorKind -linecomment -output=operator_kind_string.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownOperator-0]
	_ = x[OperatorNot-1]
	_ = x[OperatorNeg-2]
	_ = x[OperatorEllipsis-3]
	_ = x[OperatorAssign-4]
	_ = x[OperatorAddAssign-5]
	_ = x[OperatorSubAssign-6]
	_ = x[OperatorMulAssign-7]
	_ = x[OperatorDivAssign-8]
	_ = x[OperatorModAssign-9]
	_ = x[OperatorBitAndAssign-10]
	_ = x[OperatorBitOrAssign-11]
	_ = x[OperatorBitXorAssign-12]
	_ = x[OperatorBitShlAssign-13]
	_ = x[OperatorBitShrAssign-14]
	_ = x[OperatorAdd-15]
	_ = x[OperatorSub-16]
	_ = x[OperatorMul-17]
	_ = x[OperatorDiv-18]
	_ = x[OperatorMod-19]
	_ = x[OperatorEq-20]
	_ = x[OperatorNe-21]
	_ = x[OperatorLt-22]
	_ = x[OperatorLe-23]
	_ = x[OperatorGt-24]
	_ = x[OperatorGe-25]
	_ = x[OperatorBitAnd-26]
	_ = x[OperatorBitOr-27]
	_ = x[OperatorBitXor-28]
	_ = x[OperatorBitShl-29]
	_ = x[OperatorBitShr-30]
	_ = x[OperatorAnd-31]
	_ = x[OperatorOr-32]
	_ = x[OperatorAs-33]
	_ = x[OperatorRangeInclusive-34]
	_ = x[OperatorRangeExclusive-35]
	_ = x[OperatorFatArrow-36]
}

const _OperatorKind_name = "UnknownOperator!-...=+=-=*=/=%=&=|=^=<<=>>=+-*/%==!=<<=>>=&|^<<>>andoras....<=>"

var _OperatorKind_index = [...]uint8{0, 15, 16, 17, 20, 21, 23, 25, 27, 29, 31, 33, 35, 37, 40, 43, 44, 45, 46, 47, 48, 50, 52, 53, 55, 56, 58, 59, 60, 61, 63, 65, 68, 70, 72, 74, 77, 79}

func (i OperatorKind) String() string {
	if i >= OperatorKind(len(_OperatorKind_index)-1) {
		return "OperatorKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperatorKind_name[_OperatorKind_index[i]:_OperatorKind_index[i+1]]
}
