package cgen

func isRevervedWord(word string) bool {
	return reservedWords[word]
}

var reservedWords = map[string]bool{
	"auto":       true,
	"break":      true,
	"case":       true,
	"char":       true,
	"const":      true,
	"continue":   true,
	"default":    true,
	"do":         true,
	"double":     true,
	"else":       true,
	"enum":       true,
	"extern":     true,
	"float":      true,
	"for":        true,
	"goto":       true,
	"if":         true,
	"inline":     true,
	"int":        true,
	"long":       true,
	"register":   true,
	"restrict":   true,
	"return":     true,
	"short":      true,
	"signed":     true,
	"sizeof":     true,
	"static":     true,
	"struct":     true,
	"switch":     true,
	"typedef":    true,
	"union":      true,
	"unsigned":   true,
	"void":       true,
	"volitile":   true,
	"while":      true,
	"_Bool":      true,
	"_Complex":   true,
	"_Imaginary": true,
}
