// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Comment-2]
	_ = x[Type-3]
	_ = x[TypeVar-4]
	_ = x[Name-5]
	_ = x[Underscore-6]
	_ = x[Int-7]
	_ = x[Float-8]
	_ = x[String-9]
	_ = x[LParen-10]
	_ = x[RParen-11]
	_ = x[LCurly-12]
	_ = x[RCurly-13]
	_ = x[LBracket-14]
	_ = x[RBracket-15]
	_ = x[Colon-16]
	_ = x[Comma-17]
	_ = x[Eq-18]
	_ = x[EqOp-19]
	_ = x[Bang-20]
	_ = x[NeOp-21]
	_ = x[LtOp-22]
	_ = x[LeOp-23]
	_ = x[GtOp-24]
	_ = x[GeOp-25]
	_ = x[Shl-26]
	_ = x[ShlEq-27]
	_ = x[Shr-28]
	_ = x[ShrEq-29]
	_ = x[Plus-30]
	_ = x[PlusEq-31]
	_ = x[Minus-32]
	_ = x[MinusEq-33]
	_ = x[Asterisk-34]
	_ = x[AsteriskEq-35]
	_ = x[Slash-36]
	_ = x[SlashEq-37]
	_ = x[Percent-38]
	_ = x[PercentEq-39]
	_ = x[Caret-40]
	_ = x[CaretEq-41]
	_ = x[Amp-42]
	_ = x[AmpEq-43]
	_ = x[And-44]
	_ = x[AndEq-45]
	_ = x[Pipe-46]
	_ = x[PipeEq-47]
	_ = x[Or-48]
	_ = x[OrEq-49]
	_ = x[Arrow-50]
	_ = x[FatArrow-51]
	_ = x[Dot-52]
	_ = x[Dot2-53]
	_ = x[KwLet-54]
	_ = x[KwType-55]
	_ = x[KwExtern-56]
	_ = x[KwWith-57]
	_ = x[KwWhen-58]
	_ = x[KwIf-59]
	_ = x[KwElse-60]
	_ = x[KwIn-61]
	_ = x[KwAs-62]
	_ = x[KwDefer-63]
	_ = x[KwBreak-64]
	_ = x[KwReturn-65]
	_ = x[KwContinue-66]
}

const _Kind_name = "IllegalEOFCommentTypeTypeVarNameUnderscoreIntFloatStringLParenRParenLCurlyRCurlyLBracketRBracketColonCommaEqEqOpBangNeOpLtOpLeOpGtOpGeOpShlShlEqShrShrEqPlusPlusEqMinusMinusEqAsteriskAsteriskEqSlashSlashEqPercentPercentEqCaretCaretEqAmpAmpEqAndAndEqPipePipeEqOrOrEqArrowFatArrowDotDot2KwLetKwTypeKwExternKwWithKwWhenKwIfKwElseKwInKwAsKwDeferKwBreakKwReturnKwContinue"

var _Kind_index = [...]uint16{0, 7, 10, 17, 21, 28, 32, 42, 45, 50, 56, 62, 68, 74, 80, 88, 96, 101, 106, 108, 112, 116, 120, 124, 128, 132, 136, 139, 144, 147, 152, 156, 162, 167, 174, 182, 192, 197, 204, 211, 220, 225, 232, 235, 240, 243, 248, 252, 258, 260, 264, 269, 277, 280, 284, 289, 295, 303, 309, 315, 319, 325, 329, 333, 340, 347, 355, 365}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
